remote: true

experienceLevel:
  internship: false
  entry: false
  associate: false
  mid-senior level: true
  director: true
  executive: true

jobTypes:
  full-time: true
  contract: false
  part-time: false
  temporary: false
  internship: false
  other: false
  volunteer: false

date:
  all time: false
  month: false
  week: true
  24 hours: true

positions:
  - Software engineer
  - Solution Architect
  - Development Manager

locations:
  - United States

apply_once_at_company: true

distance: 100

company_blacklist:
  - Eliassen Group
  - Google
  - Apple
  - Adobe

title_blacklist:
  - word1
  - word2

job_applicants_threshold:
  min_applicants: 0
  max_applicants: 30

### OpenAI
# llm_model_type: openai
# llm_model: 'gpt-4o-mini'

### Groq
llm_model_type: openai
llm_model: 'llama3-70b-8192'
llm_api_url: 'https://api.groq.com/openai/v1'
